// <auto-generated />
namespace Dry_Cleaners.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CreditCardInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreditCardInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201609192054120_CreditCardInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
